apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift-servicemesh
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deploy Operators for OpenShift ServiceMesh
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-bundle
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/ServiceMesh/Operators
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true