kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ''
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: Job
apiVersion: batch/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: install-plan-approver
  namespace: openshift-gitops
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
    spec:
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccount: installplan-approver
      serviceAccountName: installplan-approver
      containers:
        - resources:
          name: install-plan-approver
          command:
            - /bin/sh
          imagePullPolicy: IfNotPresent
          image: >-
            openshift4/ose-cli
          args:
            - '-c'
            - >-
              oc patch installplan $(oc get ip -n openshift-operators -l operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators="" -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}') -n openshift-operators --type merge --patch '{"spec":{"approved":true}}'
