apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: operators/elasticsearch/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true