apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deploy Bookinfo ServiceMesh
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: bookinfo
  name: bookinfo
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - bookinfo
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - bookinfo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: bookinfo
  source:
    path: argocd/applications/BookInfo
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: false
#    syncOptions:
#    - CreateNamespace=true