apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: General tools for GitOps
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: templates
#  namespace: openshift-gitops
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#spec:
#  project: gitops
#  destination:
#    server: https://kubernetes.default.svc
#  source:
#    path: ArgoCD/Infra/GitOps/Openshift-Templates
#    repoURL: https://github.com/nreilly-rhn/GitOps
#    targetRevision: main
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: false
#    syncOptions:
#    - CreateNamespace=true
#---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-accounts
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/GitOps/Service-Accounts
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true