kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ''
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: Namespace
apiVersion: v1
metadata:
  labels:
    kubernetes.io/metadata.name: infra
  name: infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-admin
  namespace: infra
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cluster-admin-pipeine
subjects:
  - kind: ServiceAccount
    name: infra-admin
    namespace: infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: Job
apiVersion: batch/v1
metadata:
  name: installPlanApprover
  namespace: default
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
    spec:
      restartPolicy: Never
      schedulerName: default-scheduler
      containers:
        - resources:
          name: installPlanApprover
          command:
            - oc
          imagePullPolicy: IfNotPresent
          image: >-
            openshift4/ose-cli
          args:
            - >-
              patch installplan $(oc get ip -n my-project-o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}') -n openshift-operators --type merge --patch '{"spec":{"approved":true}}'
      serviceAccount: infra-admin
      serviceAccountName: infra-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cluster-admin-pipeine
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin