apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/ServiceMesh/Operators/elasticsearch/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/ServiceMesh/Operators/jaeger/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/ServiceMesh/Operators/kiali/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-servicemesh
  destination:
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/Infra/ServiceMesh/Operators/servicemesh/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true